### ISSUE TITLE
Improve multiline course address rendering

### ISSUE THREAD

**Issue by carlobeltrame** [UeliKurmann/pbs-kursbestaetigung#3]
When testing MiData integration, I noticed the following layout issue with multiline course addresses (kursOrt). There are no spaces or tabs before 99516 or Alt Lucienne in the payload, the indentation comes from the PDF layouter.
![image](https://user-images.githubusercontent.com/7566995/65441229-56eee400-de2a-11e9-9096-b8a697eefb41.png)
Having a multiline address for a course is rather common in hitobito, since the field is labeled Ort / Adresse. It is also possible to define multiple course parts in hitobito, each with a different location (and different start / end dates). These course parts have a single-line field labeled "Ort". But this field is less likely to be filled in my experience, since filling it is not required during course administration.

**Comment by UeliKurmann** [comment]
I can't reproduce the problem. Nevertheless, I added some cleanup logic for multiline strings. Does it work in your environment?
see: https://github.com/UeliKurmann/pbs-kursbestaetigung/commit/0729dd36f12763d82762cd085f3031e573848b0d

**Comment by carlobeltrame** [comment]
Your changes fixed it, but I found out it was an error on my side after all. I fixed it as well now, thanks!

Let me know once you've deployed.
